# Generated by Django 6.0.7 on 2026-07-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
                ('local_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('benefits_en', models.TextField(help_text='Benefits of the plant (English)')),
                ('benefits_sw', models.TextField(help_text='Faida za mmea (Kiswahili)')),
                ('medicinal_uses_en', models.TextField(help_text='Medicinal uses/treatments (English)')),
                ('medicinal_uses_sw', models.TextField(help_text='Matibabu ya dawa (Kiswahili)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
            ],
            options={
                'verbose_name': 'Medicinal Plant',
                'verbose_name_plural': 'Medicinal Plants',
                'ordering': ['local_name'],
            },
        ),
        migrations.AlterField(
            model_name='planthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planthistory',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='core.medicinalplant'),
        ),
    ]
