# Generated by Django 6.0.7 on 2026-07-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinalplant',
            name='image',
        ),
    ]
