# Generated by Django 6.0.7 on 2026-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicinalplant_common_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinalplant',
            name='precautions_en',
            field=models.TextField(blank=True, help_text='Precautions/Side effects (English)', null=True),
        ),
        migrations.AddField(
            model_name='medicinalplant',
            name='precautions_sw',
            field=models.TextField(blank=True, help_text='Tahadhari/Madhara (Kiswahili)', null=True),
        ),
        migrations.AddField(
            model_name='planthistory',
            name='precautions',
            field=models.TextField(blank=True),
        ),
    ]
